
sx_image: xcode7.3
language: objective-c
xcode_project: NinaPagerView.xcodeproj
script: xcodebuild -project NinaPagerView.xcodeproj -scheme "NinaPagerView" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest'
